version: 2.1
setup: true
orbs:
    continuation: circleci/continuation@0.1.0

jobs:
    # Fetch the tests to run
    fetch_tests:
        working_directory: ~/transformers
        docker:
            - image: cimg/python:3.7.12
        parallelism: 1
        steps:
            - checkout
            - run: pip install --upgrade pip
            - run: pip install GitPython
            - run: pip install .
            - run: mkdir -p test_preparation
            - run: python utils/tests_fetcher.py | tee tests_fetched_summary.txt
            - store_artifacts:
                path: ~/transformers/tests_fetched_summary.txt
            - run: |
                if [ -f test_list.txt ]; then
                    mv test_list.txt test_preparation/test_list.txt
                else
                    touch test_preparation/test_list.txt
                fi
            - run: |
                mkdir configs
                cp .circle_ci/config_test.yml configs/

            - persist_to_workspace:
                root: test_preparation/
                paths:
                    test_list.txt

workflows:
    version: 2
    setup-workflow:
        jobs:
            - fetch_tests
    